sudo: required
dist: bionic

language: php
php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - nightly

addons:
    apt:
        packages:
            - libssh2-1
            - libssh2-1-dev

env:
    global:
        - TEST_SSH2_HOSTNAME=localhost
        - TEST_SSH2_USER=sshuser
        - TEST_SSH2_PASS=sshpassword
        - REPORT_EXIT_STATUS=1

script:
    - ./.travis/build.sh
